In [2]:
import sys

from pathlib import Path

PROJECT_ROOT = Path().resolve().parent

sys.path.append(str(PROJECT_ROOT))

import pandas as pd

In [3]:
from src.utils.cleaning import clean_dataframe

In [4]:
EXCEL_PATH = Path(
    "../data/bronze/accounting/libro_mayor_2025.xlsx"
)

df_raw = pd.read_excel(
    EXCEL_PATH,
    engine="openpyxl",
    header=2,
)

In [5]:
df_raw.head()

,Código,Nombre de la cuenta,Fecha de factura,Contacto,Debe,Haber,Valor Final
0,110505.0,Efectivo,NaN,NaN,26082540.0,26082540.0,0.0
1,NaN,MISC/2025/03/0403 PAGO FE 52,28/03/2025,GRUPO MAREMI COLOMBIA S.A.S,0.0,56250.0,-56250.0
2,NaN,COBAN10 (MARZO AHORROS 5126) CRUCE FACTURA,31/03/2025,GRUPO MAREMI COLOMBIA S.A.S,56250.0,0.0,0.0
3,NaN,COBAN7 (MARZO BBVA) CRUCE SALDO A FAVOR,31/03/2025,ANDICOLOR S.A.,26290.0,0.0,26290.0
4,NaN,MISC/2025/03/0426 PAGO ANDICOLOR,31/03/2025,ANDICOLOR S.A.,0.0,26290.0,0.0

In [25]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 252750 entries, 0 to 252749
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Código               242 non-null     float64
 1   Nombre de la cuenta  252750 non-null  str
 2   Fecha de factura     252209 non-null  str
 3   Contacto             228484 non-null  str
 4   Debe                 252750 non-null  float64
 5   Haber                252750 non-null  float64
 6   Valor Final          252750 non-null  float64
dtypes: float64(4), str(3)
memory usage: 13.5 MB

In [18]:
print(df_raw.columns.tolist())

['Código', 'Nombre de la cuenta', 'Fecha de factura', 'Contacto', 'Debe  ', 'Haber ', 'Valor Final']

In [19]:
df_clean = clean_dataframe(
    df_raw,
    file_type="accounting",
)

2026-05-19 21:05:43,553 | INFO     | etl_pipeline | Iniciando limpieza genérica para dataset: accounting
2026-05-19 21:05:43,567 | INFO     | etl_pipeline | Normalizando nombres de columnas...
2026-05-19 21:05:43,573 | INFO     | etl_pipeline | Nombres de columnas normalizados.
2026-05-19 21:05:43,577 | INFO     | etl_pipeline | Limpiando columnas de tipo string...
2026-05-19 21:05:43,776 | INFO     | etl_pipeline | Columnas de tipo string limpiadas.
2026-05-19 21:05:43,782 | INFO     | etl_pipeline | Estandarizando valores nulos...
2026-05-19 21:05:44,224 | INFO     | etl_pipeline | Valores nulos estandarizados.
2026-05-19 21:05:44,237 | INFO     | etl_pipeline | Limpieza genérica completada. Filas: 252750, Columnas: 7

In [20]:
df_clean.head()

,cdigo,nombre_de_la_cuenta,fecha_de_factura,contacto,debe,haber,valor_final
0,110505.0,Efectivo,NaN,NaN,26082540.0,26082540.0,0.0
1,NaN,MISC/2025/03/0403 PAGO FE 52,28/03/2025,GRUPO MAREMI COLOMBIA S.A.S,0.0,56250.0,-56250.0
2,NaN,COBAN10 (MARZO AHORROS 5126) CRUCE FACTURA,31/03/2025,GRUPO MAREMI COLOMBIA S.A.S,56250.0,0.0,0.0
3,NaN,COBAN7 (MARZO BBVA) CRUCE SALDO A FAVOR,31/03/2025,ANDICOLOR S.A.,26290.0,0.0,26290.0
4,NaN,MISC/2025/03/0426 PAGO ANDICOLOR,31/03/2025,ANDICOLOR S.A.,0.0,26290.0,0.0